[package]
name = "rdfviz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdf_class_viz = { path="../lib" }
anyhow = "1.0.75"
oxigraph = "0.3.19"
